apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-config
  namespace: plexserver
spec:
  storageClassName: "nfs-conf"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: PLEX_CONF_NFS_PATH       # < NFS share path on the server
    server: NFS_SERVER_IP          # < IP address of your NFS server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-data
  namespace: plexserver
spec:
  storageClassName: "nfs-data"
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: PLEX_DATA_NFS_PATH       # < NFS share path on the server
    server: NFS_SERVER_IP          # < IP address of your NFS server
    readOnly: false
