apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-config   # < name of the persisant volume ("pv") in kubenetes
  namespace: plexserver            # < namespace where place the pv
spec:
  storageClassName: "nfs-conf"
  capacity:
    storage: 10Gi                   # < max. size we reserve for the pv
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany                # < Multiple pods can write to storage 
  persistentVolumeReclaimPolicy: Retain # < The persistent volume can reclaimed 
  nfs:
    path: /mnt/k8s/plex/conf   # < Name of your NFS share with subfolder
    server: 192.168.31.204        # < IP number of your NFS server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-data
  namespace: plexserver
spec:
  storageClassName: "nfs-data"
  capacity:
    storage: 300Gi                 # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/k8s/plex/data            
    server: 192.168.31.204
    readOnly: false
